### ISSUE TITLE
upgrade mnemonic

### ISSUE THREAD

**Issue by RCasatta** [21dotco/two1-python#5]
mnemonic package 0.13 wasn't completely compatible with python3 (https://github.com/trezor/python-mnemonic/issues/30)
could you upgrade the requirements to version 0.15 ?

**Comment by wbinns** [comment]
@RCasatta Hello, thanks for bringing this to our attention - we'll check this out.

**Comment by wbinns** [comment]
Hi @RCasatta, a quick update - we're upgrading this requirement. Thank you for the note about this. Please let us know if you have any other thoughts or suggestions!

**Comment by jianli** [comment]
Hi @RCasatta. Is there a specific bug you are encountering, or a specific use case you'd like to support?

It seems like the [python3 incompatibility fix](https://github.com/trezor/python-mnemonic/commit/d33749495eea6dbe4158d0ffb366e02b96733d40) only applies to the `to_entropy` function, which is not something we are using in `two1`.

`python-mnemonic 0.15` is less than a week old, and therefore relatively untested. For security and stability reasons, we'd rather not upgrade unnecessarily.

**Comment by RCasatta** [comment]
Sorry for not answering before, the problem is that my code is using the `to_entropy` function so I need `python-mnemonic 0.15` therefore my env is conflicting with the 21 library... Anyway it's not fundamental so I am gonna wait for the inclusion.
