### ISSUE TITLE
UnboundLocalError in payment_methods.py

### ISSUE THREAD

**Issue by febuiles** [21dotco/two1-python#8]
After seeing a report of `UnboundLocalError("local variable 'verification_response' referenced before assignment",)` in Slack I decided to take a look at the code and found this:  https://github.com/21dotco/two1-python/blob/f9d7a7c56ee86168eff0cb2b2cea8d208fe4146a/two1/bitserv/payment_methods.py#L284.

If my Python-fu is correct then `verification_response` is not in the scope at [line 285](https://github.com/21dotco/two1-python/blob/f9d7a7c56ee86168eff0cb2b2cea8d208fe4146a/two1/bitserv/payment_methods.py#L285). Maybe the `try` block should be moved to the [preceding conditional](https://github.com/21dotco/two1-python/blob/f9d7a7c56ee86168eff0cb2b2cea8d208fe4146a/two1/bitserv/payment_methods.py#L278)?

**Comment by wbinns** [comment]
@febuiles Hello, thanks for reporting this. We're currently looking into your mention with regard to the `verification_response` and will follow-up here as soon as we have an update.

**Comment by wbinns** [comment]
@febuiles Hi, this has been resolved and is currently pending deployment. Thanks again for mentioning. We look forward to hopefully seeing more of your contributions in the future!
